query fetchPRs {
			viewer {
			  pullRequests(
				orderBy: {field: CREATED_AT, direction: ASC}
				first: 100
				states: [OPEN]
			  ) {
				edges {
				  node {
					id
					repository {
					  branchProtectionRules(first: 100) {
						edges {
						  node {
							allowsDeletions
							allowsForcePushes
							requiresApprovingReviews
						  }
						}
					  }
					  name
					  url
					  owner {
						login
					  }
					}
					author{
						login
					}
					reviewDecision
					title
					baseRefName
					headRefName
					number
					permalink
					reviewRequests {
					  totalCount
					}
					reviews(first: 12) {
					  totalCount
					  nodes {
						state
					  }
					}
					mergeable
				  }
				}
			  }
			}
		  }